spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      show_sql: true
      format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog.yml
    enabled: true
